name: Tag or Commit Action
description: Outputs tag or commit
outputs:
  version:
    description: "Tag or commit"
    value: ${{ steps.script.outputs.version }}
runs:
  using: 'composite'
  steps:
    - run: echo "::set-output name=iniTime::$(date +'%Y%m%d%H%M%S')"
      id: action-started
      shell: bash
    - run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then \
            REF="${GITHUB_REF#refs/*/}"; \
        else \
            REF="${GITHUB_SHA:0:8}"; \
        fi; \
        echo "setting version as ${REF}" && \
        echo "::set-output name=version::${REF}"
      id: script
      shell: bash
    - run: ls ${HOME}/secrets/my_secret.json
    - run: ${{ github.action_path }}/sendNotify.sh ${{ steps.action-started.outputs.iniTime }}
      shell: bash 
      env: 
        SLACK_URL_WEBHOOK_DEV_TOOLS: 'http://olx.com.br'
