name: Tag or Commit Action
description: Outputs tag or commit
outputs:
  version:
    description: "Tag or commit"
    value: ${{ steps.script.outputs.versiom }}
runs:
  using: 'composite'
  steps:
    - run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then \
            REF="${GITHUB_REF#refs/*/}"; \
        else \
            REF="${GITHUB_SHA:0:8}"; \
        fi; \
        echo "setting version as ${REF}" && \
        echo "::set-output name=version::${REF}"
      id: script
      shell: bash